### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by StarfallProjects** [capeprivacy/documentation#20]
- [x] Write code of conduct, in collaboration with team
- [x] Ensure reporting process in place
- [x] Add to website -> agency

**Comment by StarfallProjects** [comment]
Blocked pending feedback / discussion with @kjam

**Comment by StarfallProjects** [comment]
https://capeprivacy.com/conduct/
